config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'

  get :login, to: 'sessions#new', as: :login
  post :login, to: 'sessions#create', as: :new_login
  delete :logout, to: 'sessions#destroy', as: :logout

  resources :users, only: [:new, :create, :show]
  resources :tweets, only: [:index, :create]
  resources :hashtags, only: :show
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  has_and_belongs_to_many :tweets

  validates :keyword, presence: true, uniqueness: true
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags

  validates :user, presence: true, associated: true

  validates :message, presence: true, length: { maximum: 140 }

  default_scope { order created_at: :desc }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :tweets

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, on: :create

  before_validation on: :create  do
    self.username = username.downcase.delete ' ' if attribute_present? "username"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  respond_to :html, :json
  responders :flash, :http_cache
  protect_from_forgery with: :exception
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  include HashtagsHelper
  before_action :set_response

  def show
    @hashtag = Hashtag.find params[:id]
    @hashtag_tweets = @hashtag.tweets

    @hashtag_tweets.each do |tweet| parse_output_for tweet: tweet end

    respond_with @response
  end

  private

  def set_response
    @response = { hashtag: @hashtag, hashtag_tweets: @hashtag_tweets }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session = session_params
    @current_user = User.find_by username: session[:username].downcase if session[:username].present?

    if @current_user && @current_user.authenticate(session[:password])
      log_in @current_user
      redirect_to tweets_path
    else
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include HashtagsHelper
  before_action :set_tweets

  def index
    @tweet = Tweet.new
    @tweets.each do |tweet| parse_output_for tweet: tweet end

    set_response
    respond_with @response
  end

  def create
    @tweet = Tweet.new tweet_params
    @tweet.user = current_user

    if @tweet.save
      parse_input_for tweet: @tweet
      set_response
      respond_with @response, location: tweets_path
    else
      render :index
    end
  end

  private

  def set_tweets
    @tweets = Tweet.all
  end

  def set_response
    @response = { tweet: @tweet, tweets: @tweets }
  end

  def tweet_params
    params.require(:tweet).permit(:message)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super
  end

  def create
    @user = User.new(user_params)
    @user.save
    respond_with(@user, location: user_path)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    if !logged_in?
      @user = User.new
      respond_with @user
    else
      redirect_to root_path
    end
  end

  def create
    @user = User.new user_params

    if @user.save
      log_in @user
      redirect_to tweets_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def parse_input_for(tweet: required)
    hashtags = hashtags_array(tweet.message)
    hashtags.each do |hashtag|
      if Hashtag.exists? keyword: hashtag
        hashtag = Hashtag.find_by keyword: hashtag
        hashtag.tweets << tweet
      else
        Hashtag.create tweet_ids: [tweet.id], keyword: hashtag
      end
   end
  end

  def parse_output_for(tweet: required)
    hashtags = hashtags_array(tweet.message)
    hashtags.each do |hashtag|
      if Hashtag.exists? keyword: hashtag
        hashtag = Hashtag.find_by keyword: hashtag
        ActionView::Base.send :include, Rails.application.routes.url_helpers
        tweet.message.gsub! hashtag.keyword, ActionController::Base.helpers.link_to(hashtag.keyword, Rails.application.routes.url_helpers.hashtag_path(hashtag))
      end
    end
  end

  private

  def hashtags_array(string)
    string.split.find_all{|word| /^#.+/.match word}.uniq
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/views/hashtags/show.html.slim
h2
  | Tweets about #{@hashtag.keyword}

- if @hashtag_tweets.any?
  - @hashtag_tweets.each do |tweet|
    p = tweet.message.html_safe
- else
  p It seems no one is talking about #{@hashtag.keyword} anymore...

= link_to "Back to Tweets", tweets_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | SimpleTweet
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = yield

app/views/tweets/_form.html.slim
= simple_form_for(@tweet) do |f|
  = f.error_notification
  .form-inputs
    = f.input :message, required: true, autofocus: true
  .form-actions
    = f.button :submit, "Tweet!"

app/views/tweets/index.html.slim
- if logged_in?
  h2
    | Hello #{current_user.username}, Spread the Tweet! Or #{link_to("log out...", logout_path, method: :delete)}
  = render 'form'
  = link_to "View my Tweets", user_path(current_user)
- else
  h2
    | Hello, #{link_to("sign in", login_path)} or #{link_to("sign up", new_user_path)} to Spread the Tweet!

- if @tweets.any?
  h2
    | Latests Tweets
  table.table
    thead
      tr
        th = :message
        th = :user
        th = :created_at

    tbody
      - @tweets.each do |tweet|
        tr
          td = tweet.message.html_safe
          td = link_to tweet.user.username, user_path(tweet.user)
          td = tweet.created_at

app/views/users/_form.html.slim
= simple_form_for(@user) do |f|
  = f.error_notification
  .form-inputs
    = f.input :username, required: true, autofocus: true
    = f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum")
    = f.input :password_confirmation, required: true
  .form-actions
    = f.button :submit, "Sign up"

app/views/users/new.html.slim
h2
  | Sign up

= render 'form'

p Already signed up? #{link_to("Sign in now!", login_path)}

app/views/users/show.html.slim
h2
  | #{@user.username} Tweets

- if @user.tweets.any?
  - @user.tweets.each do |tweet|
    - parse_output_for tweet: tweet
    p = tweet.message.html_safe
- else
  p #{@user.username} appears to be shy and haven't spread the Tweet yet!

= link_to "Back to Tweets", tweets_path